const texCharacters = {
"\\alpha" : "α",
"\\beta" : "β",
"\\gamma" : "γ",
"\\delta" : "δ",
"\\epsilon" : "ε",
"\\zeta" : "ζ",
"\\eta" : "η",
"\\theta" : "θ",
"\\iota" : "ι",
"\\kappa" : "κ",
"\\lambda" : "λ",
"\\mu" : "μ",
"\\nu" : "ν",
"\\xi" : "ξ",
"\\pi" : "π",
"\\rho" : "ρ",
"\\sigma" : "σ",
"\\tau" : "τ",
"\\upsilon" : "υ",
"\\phi" : "φ",
"\\chi" : "χ",
"\\psi" : "ψ",
"\\omega" : "ω",
"\\Gamma" : "Γ",
"\\Delta" : "Δ",
"\\Theta" : "Θ",
"\\Lambda" : "Λ",
"\\Xi" : "Ξ",
"\\Pi" : "Π",
"\\Sigma" : "Σ",
"\\Upsilon" : "Υ",
"\\Phi" : "Φ",
"\\Psi" : "Ψ",
"\\Omega" : "Ω",
"\\varepsilon" : "ϵ",
"\\vartheta" : "ϑ",
"\\varpi" : "ϖ",
"\\varrho" : "ϱ",
"\\varsigma" : "ς",
"\\varphi" : "φ",

"\\infty" : "∞",
};

export default texCharacters;